app = "startupproxpert"  # Nome do seu aplicativo

[build]
  dockerfile = "Dockerfile"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]

  [[http_services]]
    port = 8080
    handlers = ["http"]
